# Generated by Django 5.0.6 on 2025-07-14 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_alter_category_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, verbose_name='动态配置'),
        ),
        migrations.CreateModel(
            name='SKUAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='自定义值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_attribute_values', to='products.attribute', verbose_name='属性')),
                ('attribute_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_attribute_values', to='products.attributevalue', verbose_name='属性值')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_attribute_values', to='products.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'SKU属性值',
                'verbose_name_plural': 'SKU属性值',
                'ordering': ['sku', 'attribute__order'],
                'indexes': [models.Index(fields=['sku', 'attribute'], name='products_sk_sku_id_3115e0_idx'), models.Index(fields=['attribute', 'attribute_value'], name='products_sk_attribu_cccada_idx')],
                'unique_together': {('sku', 'attribute')},
            },
        ),
    ]
