# Generated by Django 5.0.6 on 2025-07-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_comments_and_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='remarks',
            field=models.TextField(blank=True, db_comment='产品的补充说明信息，如配件、特殊说明等', default='', help_text='产品的额外补充说明，如：一块可调节隔板', verbose_name='备注说明'),
        ),
    ]
