# Generated by Django 5.0.6 on 2025-07-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_board_level_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='configuration',
        ),
    ]
