# Generated by Django 5.0.6 on 2025-07-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_json_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['-created_at'], 'verbose_name': 'SKU产品', 'verbose_name_plural': 'SKU产品'},
        ),
        migrations.AlterModelOptions(
            name='spu',
            options={'ordering': ['-created_at'], 'verbose_name': 'SPU产品单元', 'verbose_name_plural': 'SPU产品单元'},
        ),
        migrations.AlterModelTableComment(
            name='spu',
            table_comment='SPU产品单元(SPU)表 - 定义产品的通用属性和模板',
        ),
    ]
