# Generated by Django 5.0.6 on 2025-07-18 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_sku_level_pricing_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPUDimensionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_type', models.CharField(choices=[('height', '高度'), ('width', '宽度'), ('depth', '厚度/深度'), ('length', '长度'), ('diameter', '直径'), ('radius', '半径'), ('area', '面积'), ('volume', '体积'), ('weight', '重量'), ('custom', '自定义')], db_comment='尺寸的类型，如高度、宽度、厚度等', help_text='选择尺寸的类型', max_length=20, verbose_name='尺寸类型')),
                ('default_value', models.DecimalField(db_comment='SPU的默认尺寸值', decimal_places=2, help_text='基于此SPU创建SKU时的默认尺寸值', max_digits=10, verbose_name='默认值')),
                ('min_value', models.DecimalField(blank=True, db_comment='允许的最小尺寸值', decimal_places=2, help_text='允许的最小尺寸值，为空表示无限制', max_digits=10, null=True, verbose_name='最小值')),
                ('max_value', models.DecimalField(blank=True, db_comment='允许的最大尺寸值', decimal_places=2, help_text='允许的最大尺寸值，为空表示无限制', max_digits=10, null=True, verbose_name='最大值')),
                ('unit', models.CharField(choices=[('mm', '毫米'), ('cm', '厘米'), ('m', '米'), ('㎡', '平方米'), ('m³', '立方米'), ('kg', '千克'), ('g', '克'), ('custom', '自定义单位')], db_comment='尺寸的计量单位', default='mm', help_text='尺寸的计量单位', max_length=10, verbose_name='单位')),
                ('custom_unit', models.CharField(blank=True, db_comment='自定义的计量单位', default='', help_text='当单位选择为自定义时，填写具体的单位名称', max_length=20, verbose_name='自定义单位')),
                ('tolerance', models.DecimalField(db_comment='尺寸的允许公差范围', decimal_places=2, default=0.0, help_text='尺寸的允许公差范围，±值', max_digits=10, verbose_name='公差')),
                ('is_required', models.BooleanField(db_comment='基于此SPU创建SKU时是否必须设置此尺寸', default=True, help_text='勾选后基于此SPU创建SKU时必须设置此尺寸', verbose_name='是否必填')),
                ('is_key_dimension', models.BooleanField(db_comment='是否为影响定价的关键尺寸', default=False, help_text='是否为影响定价的关键尺寸', verbose_name='是否关键尺寸')),
                ('description', models.TextField(blank=True, db_comment='尺寸的详细描述和说明', default='', help_text='尺寸的详细描述，包括测量方法、特殊说明等', verbose_name='尺寸描述')),
                ('order', models.IntegerField(db_comment='尺寸在SPU下的显示顺序', default=0, help_text='在产品尺寸配置界面的显示顺序', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建的时间戳', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新的时间戳', verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, db_comment='创建此记录的用户ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spu_dimension_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('spu', models.ForeignKey(db_comment='关联的SPU产品单元', help_text='此尺寸模板所属的SPU', on_delete=django.db.models.deletion.CASCADE, related_name='dimension_templates', to='products.spu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': 'SPU尺寸模板',
                'verbose_name_plural': 'SPU尺寸模板',
                'db_table_comment': 'SPU尺寸模板表 - 定义SPU级别的标准尺寸模板',
                'ordering': ['spu', 'order', 'dimension_type'],
                'indexes': [models.Index(fields=['spu'], name='idx_spu_dim_tmpl_spu'), models.Index(fields=['dimension_type'], name='idx_spu_dim_tmpl_type'), models.Index(fields=['is_key_dimension'], name='idx_spu_dim_tmpl_key'), models.Index(fields=['order'], name='idx_spu_dim_tmpl_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='spudimensiontemplate',
            constraint=models.UniqueConstraint(fields=('spu', 'dimension_type'), name='unique_spu_dim_tmpl_per_type'),
        ),
    ]
