# Generated by Django 5.0.6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_spu_dimension_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('name', models.CharField(help_text='导入任务的名称', max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('products', '产品数据'), ('categories', '分类数据'), ('brands', '品牌数据'), ('attributes', '属性数据'), ('mixed', '混合数据')], default='products', max_length=20, verbose_name='导入类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('partial', '部分成功')], default='pending', max_length=20, verbose_name='任务状态')),
                ('file_path', models.FileField(help_text='上传的Excel文件', upload_to='import/files/', verbose_name='导入文件')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='已处理行数')),
                ('success_rows', models.IntegerField(default=0, verbose_name='成功行数')),
                ('error_rows', models.IntegerField(default=0, verbose_name='错误行数')),
                ('progress', models.FloatField(default=0.0, help_text='0-100', verbose_name='进度百分比')),
                ('result_summary', models.JSONField(default=dict, help_text='导入结果的详细统计', verbose_name='结果摘要')),
                ('error_details', models.TextField(blank=True, help_text='导入过程中的错误信息', verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '导入任务',
                'verbose_name_plural': '导入任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('products', '产品数据'), ('categories', '分类数据'), ('brands', '品牌数据'), ('attributes', '属性数据'), ('mixed', '混合数据')], max_length=20, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('field_mapping', models.JSONField(help_text='Excel列名到模型字段的映射关系', verbose_name='字段映射')),
                ('required_fields', models.JSONField(default=list, help_text='必须提供的字段列表', verbose_name='必填字段')),
                ('validation_rules', models.JSONField(default=dict, help_text='字段验证规则', verbose_name='验证规则')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '导入模板',
                'verbose_name_plural': '导入模板',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='行号')),
                ('error_type', models.CharField(choices=[('validation', '数据验证错误'), ('format', '格式错误'), ('duplicate', '重复数据'), ('reference', '引用错误'), ('system', '系统错误')], max_length=20, verbose_name='错误类型')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='字段名')),
                ('error_message', models.TextField(verbose_name='错误消息')),
                ('raw_data', models.JSONField(help_text='导致错误的原始行数据', verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='products.importtask', verbose_name='导入任务')),
            ],
            options={
                'verbose_name': '导入错误',
                'verbose_name_plural': '导入错误',
                'ordering': ['task', 'row_number'],
            },
        ),
    ]